openapi: 3.0.0
info:
  title: Posting-System API
  version: 1.0.0
  description: API for managing posts in a database
servers:
  - url: "http://localhost:7777"
paths:
  /api/items:
    get:
      summary: Get all posts
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Post"
    post:
      summary: Create a new post
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                type: string
      responses:
        "200":
          description: Successful response
  /api/items/{id}:
    put:
      summary: Update a post
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Post"
      responses:
        "200":
          description: Successful response
    delete:
      summary: Delete a post
      parameters:
        - in: query
          name: id
          required: false
          schema:
            type: string
      responses:
        "200":
          description: Successful response

components:
  schemas:
    Post:
      type: object
      properties:
        _id:
          type: string
        content:
          type: string
        isDeleted:
          type: boolean
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
